openapi: "3.0.3"
info:
  title: "Customer Service API"
  version: "1.0.0"
servers:
  - url: "https://customer-service"
paths:
  /owners/{ownerId}:
    put:
      summary: "PUT owners/{ownerId}"
      operationId: "updateOwner"
      parameters:
        - name: "ownerId"
          in: "path"
          required: true
          schema:
            type: "integer"
            format: "int32"
      requestBody:
        content:
          application/json:
            schema:
              $ref: "#/components/schemas/Owner"
        required: true
      responses:
        "204":
          description: "No Content"
    get:
      summary: "GET owners/{ownerId}"
      operationId: "findOwner"
      parameters:
        - name: "ownerId"
          in: "path"
          required: true
          schema:
            type: "integer"
            format: "int32"
      responses:
        "200":
          description: "OK"
          content:
            '*/*':
              schema:
                $ref: "#/components/schemas/Owner"
  /owners:
    post:
      summary: "POST owners"
      operationId: "createOwner"
      requestBody:
        content:
          application/json:
            schema:
              $ref: "#/components/schemas/Owner"
        required: true
      responses:
        "201":
          description: "Created"
          content:
            '*/*':
              schema:
                $ref: "#/components/schemas/Owner"
    get:
      summary: "GET owners"
      operationId: "findAll"
      responses:
        "200":
          description: "OK"
          content:
            '*/*':
              schema:
                type: "array"
                items:
                  $ref: "#/components/schemas/Owner"
  /owners/{variable}/pets/{petId}:
    put:
      summary: "PUT owners/*/pets/{petId}"
      operationId: "processUpdateForm"
      parameters:
        - name: "petId"
          in: "path"
          required: false
      requestBody:
        content:
          application/json:
            schema:
              $ref: "#/components/schemas/PetRequest"
        required: true
      responses:
        "204":
          description: "No Content"
    get:
      summary: "GET owners/*/pets/{petId}"
      operationId: "findPet"
      parameters:
        - name: "petId"
          in: "path"
          required: true
          schema:
            type: "integer"
            format: "int32"
      responses:
        "200":
          description: "OK"
          content:
            '*/*':
              schema:
                $ref: "#/components/schemas/PetDetails"
  /owners/{ownerId}/pets:
    post:
      summary: "POST owners/{ownerId}/pets"
      operationId: "processCreationForm"
      parameters:
        - name: "ownerId"
          in: "path"
          required: true
          schema:
            type: "integer"
            format: "int32"
      requestBody:
        content:
          application/json:
            schema:
              $ref: "#/components/schemas/PetRequest"
        required: true
      responses:
        "201":
          description: "Created"
          content:
            '*/*':
              schema:
                $ref: "#/components/schemas/Pet"
  /petTypes:
    get:
      summary: "GET petTypes"
      operationId: "getPetTypes"
      responses:
        "200":
          description: "OK"
          content:
            '*/*':
              schema:
                type: "array"
                items:
                  $ref: "#/components/schemas/PetType"
components:
  schemas:
    PetType:
      type: "object"
      properties:
        id:
          type: "integer"
          format: "int32"
        name:
          type: "string"
    Pet:
      type: "object"
      properties:
        id:
          type: "integer"
          format: "int32"
        name:
          type: "string"
        birthDate:
          type: "string"
          format: "date-time"
        type:
          $ref: "#/components/schemas/PetType"
    Owner:
      type: "object"
      properties:
        id:
          type: "integer"
          format: "int32"
        firstName:
          type: "string"
        lastName:
          type: "string"
        address:
          type: "string"
        city:
          type: "string"
        telephone:
          type: "string"
        pets:
          type: "array"
          items:
            $ref: "#/components/schemas/Pet"
    PetRequest:
      type: "object"
      properties:
        id:
          type: "integer"
          format: "int32"
        birthDate:
          type: "string"
          format: "date-time"
        name:
          type: "string"
        typeId:
          type: "integer"
          format: "int32"
    PetDetails:
      type: "object"
      properties:
        id:
          type: "integer"
          format: "int64"
        name:
          type: "string"
        owner:
          type: "string"
        birthDate:
          type: "string"
          format: "date-time"
        type:
          $ref: "#/components/schemas/PetType"